version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: winterborn
      POSTGRES_USER: postgres
      POSTGRES_DB: ina_zaoui
volumes:
  postgres_db:
    driver: local