version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env:
      - POSTGRES_PASSWORD=DATABASE_PASSWORD
      - POSTGRES_USER=DATABASE_USER
      - POSTGRES_DB=DATABASE_NAME
volumes:
  postgres_db:
    driver: local