name: Continuous integration
on: [push]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["8.2", "8.3"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          tools: composer, castor

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Build Project
        run: |
          if [ -f "docker-compose.yml" ]; then
            docker compose -f "docker-compose.yml" up -d --build
          fi
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
          php bin/console sass:build || echo "SASS build failed, continuing..."

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit

      - name: Run PHPStan Analysis
        run: vendor/bin/phpstan analyse src --level=max
